server:
# Log Encoding
  servlet:
    encoding:
      force-response: true
      charset: UTF-8


spring:
# JPA Settings
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true # SQL Pretty Print
    open-in-view: false # OSIV 옵션 Off (성능)

  # H2 Settings
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:shop
    driver-class-name: org.h2.Driver

# Logging Settings
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace # 쿼리 파라미터 로깅